apiVersion: v1
kind: Namespace
metadata:
  name: elastic-synthetic-monitoring
  labels:
    name: elastic-synthetic-monitoring
    monitoring: synthetic
    app.kubernetes.io/name: elastic-synthetic-monitoring
    app.kubernetes.io/component: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-agent
  namespace: elastic-synthetic-monitoring
  labels:
    app.kubernetes.io/name: elastic-agent
    app.kubernetes.io/component: monitoring-agent
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastic-agent-synthetics
  labels:
    app.kubernetes.io/name: elastic-agent-synthetics
    app.kubernetes.io/component: monitoring-agent
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
- apiGroups: [""]
  resources:
  - nodes
  - namespaces
  - events
  - pods
  - services
  - configmaps
  - secrets
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  - deployments
  - replicasets
  - daemonsets
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elastic-agent-synthetics
  labels:
    app.kubernetes.io/name: elastic-agent-synthetics
    app.kubernetes.io/component: monitoring-agent
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
- kind: ServiceAccount
  name: elastic-agent
  namespace: elastic-synthetic-monitoring
roleRef:
  kind: ClusterRole
  name: elastic-agent-synthetics
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kibana-sync-service
  namespace: elastic-synthetic-monitoring
  labels:
    app.kubernetes.io/name: kibana-sync-service
    app.kubernetes.io/component: sync-service
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kibana-sync-service
  namespace: elastic-synthetic-monitoring
  labels:
    app.kubernetes.io/name: kibana-sync-service
    app.kubernetes.io/component: sync-service
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - events
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kibana-sync-service
  namespace: elastic-synthetic-monitoring
  labels:
    app.kubernetes.io/name: kibana-sync-service
    app.kubernetes.io/component: sync-service
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
- kind: ServiceAccount
  name: kibana-sync-service
  namespace: elastic-synthetic-monitoring
roleRef:
  kind: Role
  name: kibana-sync-service
  apiGroup: rbac.authorization.k8s.io
